M3SOSCF Implementation
pyscf/pyscf-forge pull request #47
Opened 2024-05-08 18:43 UTC by LinusBDittmer

This is an implementation of the Markovian Multiagent Monte-Carlo SOSCF based on CIAH. It is a powerful, albeit slow SCF algorithm that enables near-guaranteed convergence even in extremely difficult systems.

Publication: [https://doi.org/10.1063/5.0159737](https://doi.org/10.1063/5.0159737)

See also [PR#2208 in pyscf/pyscf](https://github.com/pyscf/pyscf/pull/2208).

2024-05-09 15:33 UTC, matthew-hennefarth requested changes

2024-05-09 15:33 UTC, matthew-hennefarth commented on pyscf/scf/hf.py
This file is the same as that in the main [PySCF repository](https://github.com/pyscf/pyscf/blob/master/pyscf/scf/hf.py). You should not copy those files into this repository. Instead, you should import this file using the appropriate method from the main PySCF directory.

2024-05-09 15:33 UTC, matthew-hennefarth commented on pyscf/soscf/test/test_m3soscf.py
> +# Copyright 2014-2019 The PySCF Developers. All Rights Reserved.
Update copyright to 2024

2024-05-09 15:33 UTC, matthew-hennefarth commented on pyscf/soscf/__init__.py
> +# Copyright 2014-2018 The PySCF Developers. All Rights Reserved.
Update Copyright to 2024

2024-05-09 15:33 UTC, matthew-hennefarth commented on pyscf/soscf/m3soscf.py
> +'''
Add copyright comment banner.

2024-05-09 15:33 UTC, matthew-hennefarth commented on pyscf/soscf/sigma_utils.py
> +'''
Add copyright banner

2024-05-09 15:46 UTC, matthew-hennefarth commented
Can you please add an example of this functionality.

2024-05-09 15:47 UTC, LinusBDittmer commented on pyscf/scf/hf.py
I added a decorated to the SCF base class in hf.py that allows for the creation of an M3SOSCF object analogously to the CIAH implementation. Should I add this differently, and if so, what specifications should I follow?

2024-05-09 15:54 UTC, LinusBDittmer commented
An example has been added in examples/scf. Copyright banners have been updated/added.

2024-05-09 17:29 UTC, matthew-hennefarth commented on pyscf/soscf/__init__.py
This file should be deleted since it will cause import clashes later on down the line with that in the main branch.

2024-05-09 17:54 UTC, matthew-hennefarth commented on pyscf/scf/hf.py
I believe so otherwise there will be import clashes. That is, when someone does 

```python
import pyscf.scf.hf
```
or 
```python
from pyscf.scf import hf
```

It is somewhat undefined which `hf.py` to import, that from pyscf or from pyscf-forge. I am not sure the best way of doing this to get the desired result. This is because pyscf-forge is built such that it doesn't really modify the internal structure of classes from pyscf. One could get around this by constructing a new SCF object that inherits the SCF object from pyscf/pyscf/scf/hf.py but then adds on the `m3soscf` method. This would again have to be implemented such that there are no import conflicts from the main repo though.

2024-05-09 17:56 UTC, matthew-hennefarth commented on pyscf/scf/hf.py
One possibility, but this is more of a general design decision for pyscf-forge, is to place all of your new code in a subfolder m3soscf. This would prevent import clashes as the hf.py would be in pyscf.m3soscf.scf.hf instead. But in general, I am not sure of the correct way of doing this for this project.

2024-05-09 18:07 UTC, LinusBDittmer commented on pyscf/scf/hf.py
I suggest that I remove hf.py for now, as there still is a straightforward constructor without it instead. If an M3SOSCF implementation is merged into pyscf proper, the decorator can still be added.

2024-05-09 18:09 UTC, LinusBDittmer commented
soscf/__init__.py as well as scf/hf.py have been removed. Since there are no other files in scf/, I have removed the directory entirely.

2024-05-09 19:31 UTC, matthew-hennefarth commented
It should be good so long as all tests pass, @sunqm can you please approve for the workflows?

2024-05-09 20:47 UTC, LinusBDittmer commented
I still had the old import statements from developing inside a forked repo of pyscf proper, I changed these to work for pyscf-forge.

2024-05-11 20:18 UTC, sunqm commented
> It should be good so long as all tests pass, @sunqm can you please approve for the workflows?

Thank you for reviewing the PR code!

2024-05-11 20:18 UTC, merged

2024-05-12 20:22 UTC, LinusBDittmer commented
@matthew-hennefarth Thank you for the review. @sunqm Is there anything I can do, any information I can provide, regarding possible discussion on whether this feature will be merged into the main branch of PySCF?